name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Copy files to Dockerfile directory
      run: cp -r example ./docker/
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: docker/Dockerfile
        push: true
        tags: aie-developer:$(date +%s)
